site_name: Limiti degli LLM
theme:
  name: material
  language: it
  palette:
    - scheme: default # Tema chiaro
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: ModalitÃ  notte
    - scheme: slate # Tema scuro
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: ModalitÃ  giorno
  features:
    - navigation.tabs
    - search.suggest
    - content.code.copy

nav:
  - Home: index.md
  - ðŸ›  Procedure: 
      - procedure/setup.md
      - procedure/linee-guida.md
  - ðŸš€ Progetti: 
      - progetti/progetto-A.md